### ISSUE TITLE
error about running generate_results.py

### ISSUE THREAD

**Issue by zhengshi119** [zju3dv/text_scene_motion#5]
when I run the generate_results.py，there is a error： 
ret  <function process_clip_text at 0x74c8ad7e8af0>
Traceback (most recent call last):
  File "/root/workspace_zs/text_scene_motion-main/tools/generate_results.py", line 155, in <module>
    main(cfg, data_loader)
  File "/root/workspace_zs/text_scene_motion-main/tools/generate_results.py", line 136, in main
    run_network(network, data_loader)
  File "/root/workspace_zs/text_scene_motion-main/tools/generate_results.py", line 93, in run_network
    network(batch, inference=True, compute_supervision=False, compute_loss=False)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/wrapper/wrapper.py", line 166, in forward
    self.path_net.inference(batch)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffuser_network.py", line 80, in inference
    batch['ksamples'] = ksamples = self.diffuser.sample(batch, k=k, init_x=init_x)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffusion/ddpm_base.py", line 132, in sample
    ksamples.append(self.p_sample_loop(data, init_x=init_x))
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffusion/ddpm_base.py", line 342, in p_sample_loop
    x_t = self.p_sample(x_t, t, data, init_x=init_x)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffusion/ddpm_base.py", line 208, in p_sample
    model_mean, model_variance, model_log_variance = self.p_mean_variance(x_t, batch_timestep, data, clip_denoised=True, init_x=init_x)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffusion/ddpm_base.py", line 239, in p_mean_variance
    pred_noise, pred_x0 = self.model_predict(x_t, t, data)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/diffusion/ddpm_base.py", line 268, in model_predict
    pred = self.eps_model(x_t, t, data)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/model/eps_model.py", line 98, in forward
    cond, cond_mask = self.condition(batch, x_t)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/model/eps_model.py", line 190, in condition
    sensor_feat, sensor_mask = self.get_sensor_feat(batch, x_t)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/model/eps_model.py", line 230, in get_sensor_feat
    target_voxel, target_points, target_nn_normal = self.target_sensor.forward(batch)
  File "/root/workspace_zs/text_scene_motion-main/lib/networks/model/sensor.py", line 100, in forward
    r = (obj_points.max(dim=0)[0] - obj_points.min(dim=0)[0]).max() * 0.5
IndexError: max(): Expected reduction dim 0 to have non-zero size.

**Comment by BadaLeexxx** [comment]
I encountered the same issue. May I ask if you have resolved it?
